---
- name: Add virtual server
  bigip_virtual_server:
    state: present
    partition: "{{ partition }}"
    name: "{{ vs_name }}"
    destination: "{{ destination }}"
    port: "{{ port }}"
    pool: "{{ pool_name }}"
    snat: "{{ snat }}"
    description: "{{ description }}"
    policies: "{{ item.policies }}"
    enabled_vlans: "{{ item.enabled_vlans }}"
    ip_protocol: "{{ ip_protocol }}"
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
    loop: "{{ policies.split('\n') }}"
    loop: "{{ enabled_vlans.split('\n') }}"
  delegate_to: localhost
