- name: Create client SSL profile with specific ciphers
  bigip_profile_client_ssl:
    state: present
    name: "{{ profile_name }}"
    cert_key_chain:
      - cert: "{{ cert_name }}"
        key: "{{ key_name }}"
    ciphers: "{{ ciphers }}" #!SSLv3:!SSLv2:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
  delegate_to: localhost
