---
- name: Add virtual server
  set_fact:
    state: present
    partition: "{{ partition }}"
    name: "{{ vs_name }}"
    destination: "{{ destination }}"
    port: "{{ port }}"
    pool: "{{ pool_name }}"
    snat: "{{ snat }}"
    description: "{{ description }}"
    profiles:
      - http
      - fix
      - name: clientssl
        context: server-side
      - name: ilx
        context: client-side
    policies: "{{ policies }}"
    enabled_vlans: "{{ enabled_vlans }}"
    ip_protocol: "{{ ip_protocol }}"
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
  delegate_to: localhost
- debug:
    var: state
- debug:
    var: partition
- debug:
    var: name
- debug:
    var: destination
- debug:
    var: port
- debug:
    var: pool
- debug:
    var: snat
- debug:
    var: description
- debug:
    var: profiles
- debug:
    var: policies
- debug:
    var: enabled_vlans
- debug:
    var: ip_protocol
- debug:
    var: provider
- debug:
    var: item.enabled_vlans
- debug:
    var: f5_ip
- debug:
    var: f5_username
- debug:
    var: f5_password