---
- name: Add virtual server
  set_fact:
    state: present
    partition: "{{ partition }}"
    name: "{{ vs_name }}"
    destination: "{{ destination }}"
    port: "{{ port }}"
    pool: "{{ pool_name }}"
    snat: "{{ snat }}"
    description: "{{ description }}"
    profiles:
      - http
      - fix
      - name: clientssl
        context: server-side
      - name: ilx
        context: client-side
    policies: "{{ policies }}"
    enabled_vlans: "{{ item.enabled_vlans }}"
    ip_protocol: "{{ ip_protocol }}"
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
  delegate_to: localhost
